### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: accessories.forEach is not a function

### ISSUE THREAD

**Issue by hughfr4nc15** [ptz0n/homebridge-securitas-direct#3]
Hello,

When I install the plugin, my Homebridge Server does not start and throws the following error:

```
(node:4688) UnhandledPromiseRejectionWarning: TypeError: accessories.forEach is not a function
    at C:\Program Files\nodejs\node_modules\homebridge\src\server.ts:417:21
    at C:\Program Files\nodejs\node_modules\homebridge\node_modules\hap-nodejs\src\lib\util\once.ts:10:18
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4688) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:4688) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Can you please help?

Thanks.

**Comment by ptz0n** [comment]
Hi & thanks for reaching out! Is there any other output in the logs? These lines only have references to Homebridge which makes it a bit harder to debug.

**Comment by hughfr4nc15** [comment]
Hello Erik,

So I reinstalled the plugin, this time with user and password in the config instead of Environment Variables and the error did not show up.

(btw: how do I enter the Environment Variables properly in the config file? Only need to replace the user and password by the Variable? With or without " "?)

It shows that is it polling in the logs:

`[12/15/2020, 2:05:27 AM] [Securitas Direct] info Alarm: Getting current alarm state.
[12/15/2020, 2:05:27 AM] [Securitas Direct] info Alarm: Getting current alarm state.
[12/15/2020, 2:05:29 AM] [Securitas Direct] info Alarm: Getting current alarm state.
[12/15/2020, 2:05:29 AM] [Securitas Direct] info Alarm: Getting current alarm state.
[12/15/2020, 2:06:06 AM] [Securitas Direct] info Alarm: Getting current alarm state.`

But in the Home app I get the "This accessory is not responding." error now...

Something I might be missing?

Thanks!

**Comment by ptz0n** [comment]
There is two ways of setting your credentials, either in your config.json, or via environment variables. You should not put any environment variables into your config.json file.

According to your logs, the installation seem to work fine, good job!

Regarding the Home app giving showing "Not responding". I recommend that you are running Homebridge on a wired connection, not WiFi.

Are you controlling Homebridge from your local network or remotely?

**Comment by hughfr4nc15** [comment]
When I replaced the user and password in the .json file by the environment variable and restarted Homebridge the error is back and the server fails to start. After re-adding the user and password to the file the error is gone and the server starts again

![image](https://user-images.githubusercontent.com/16179664/102283517-7b047c80-3f2a-11eb-8e31-a19249bb0b31.png)

I assume it should have something to do with it... or I'm using the variables wrong.

This is my config that starts the server but the alarm shows as "No Response".

![image](https://user-images.githubusercontent.com/16179664/102284170-9cb23380-3f2b-11eb-941b-74330a307acc.png)

I'm using Homebridge on my local network and on Wi-Fi (Server is 1m away from the RTR).

And this is my alarm:

![image](https://user-images.githubusercontent.com/16179664/102284288-d5eaa380-3f2b-11eb-8e8c-246e75871989.png)

Is this the correct plug-in?

Thanks for your help.

**Comment by hughfr4nc15** [comment]
When I replaced the user and password in the .json file by the environment variable and restarted Homebridge the error is back and the server fails to start. After re-adding the user and password to the file the error is gone and the server starts again

![image](https://user-images.githubusercontent.com/16179664/102283517-7b047c80-3f2a-11eb-8e31-a19249bb0b31.png)

I assume it should have something to do with it... or I'm using the variables wrong.

This is my config that starts the server but the alarm shows as "No Response".

![image](https://user-images.githubusercontent.com/16179664/102284401-ffa3ca80-3f2b-11eb-86eb-a8d3a9e23601.png)

I'm using Homebridge on my local network and on Wi-Fi (Server is 1m away from the RTR).

And this is my alarm:

![image](https://user-images.githubusercontent.com/16179664/102284288-d5eaa380-3f2b-11eb-8e8c-246e75871989.png)

Is this the correct plug-in?

Thanks for your help.

**Comment by hughfr4nc15** [comment]
When I replaced the user and password in the .json file by the environment variable and restarted Homebridge the error is back and the server fails to start. After re-adding the user and password to the file the error is gone and the server starts again.

![image](https://user-images.githubusercontent.com/16179664/102283517-7b047c80-3f2a-11eb-8e31-a19249bb0b31.png)

I assume it should have something to do with it... or I'm using the variables wrong.

The "No response" issue was due to the fact that it was a new account and you need to enter a new password in the first login. After setting it up, all worked fine. Only issue now is using the variables.

By the way, is there any issue/quota for constantly asking the alarm status to Securitas?

**Comment by ptz0n** [comment]
Great and thanks for your insight.

I would not recommend setting global environment variables. This will make them available to all applications on your system. Rather, I prefer to set them per application to minimise exposure.

Are you running Homebridge using some kind of process manager?

During my testing, I have not yet run into any issues with the current polling frequency. It's currently set to every minute (60s) and can be tweaked to your preference using the config.

**Comment by hughfr4nc15** [comment]
Would you please give me some tips on how to configure the Environment Variables per app?

Hummm... I just installed it on an Intel NUC running Win10 that is on all the time.

**Comment by hughfr4nc15** [comment]
@ptz0n Would you share the steps to configure the Environment Variables per application?

Thanks in advance.

**Comment by hughfr4nc15** [comment]
I configured the plugin and tested for a while and it seems that it is not reliable enough for daily use. Don't get me wrong, thank you for your work, but while testing it, the alarm status would not change correctly sometimes or would show up as disarming for no reason.
Being about home security, I believe something more reliable is needed so I'll stick to the App for now.

**Comment by ptz0n** [comment]
Thanks for your feedback @hughfr4nc15! I know that any state change takes a while to settle, this is due to the slow interface of Securitas Direct.

Interesting that alarm statuses is not changed correctly, can you please share more info about that? Might just be that it takes a while to settle?
